### ISSUE TITLE
Sonification query parameter

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/john-travoltage#141]
Current values are 0, 1, 2, 3 and 4. If this is permanent, named query parameter values would presumably be much more helpful.

Code review for https://github.com/phetsims/john-travoltage/issues/128

**Comment by jessegreenberg** [comment]
These are not meant to be permanent but are still being used to prototype different styles.  Named values do seem helpful, I renamed 0-4 to [ 'none', 'piano', 'pitch', 'jostle', 'transformer' ] based on descriptions in JohnTravoltageQueryParameters.

@jbphet does this look OK?

**Comment by jonathanolson** [comment]
The JSDoc should also be updated:
```
@param {number} sonificationControl
```

**Comment by jbphet** [comment]
This is not supposed to be permanent - eventually these will be narrowed down to one set of sounds to use for sonification and the ability to select them via the query parameter will be removed.  Having said this, this has lived on longer than I expected, and has been useful for demos, so we might as well maintain the code in a reasonable fashion.  The names are not perfect, since it is actually a *set* of sounds that is being selected by the query parameter value and not just a single sound, but this is probably better than arbitrary numbers.  So yeah, it looks OK to me.  Closing.

**Comment by jonathanolson** [comment]
JSDoc note not updated, reopening.

**Comment by jessegreenberg** [comment]
fixed the JSDoc, closing.
