### ISSUE TITLE
Delay for loading audio data

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/john-travoltage#163]
In ChargeAmountSoundGenerator, a VIBE/Sound is created, yet we have to wait for it to load the sound data.

It seems like the purpose of the sim loading time is to wait for that type of operation, so that sims won't have to do this in their operations.

For instance, with images, it takes the data URLs and waits until the image information is loaded. Why can't we do the same with audio?

@samreid and @jbphet, would this be possible? Can we have ```audiobuffer!``` or ```sound!``` plugins that can do this? It would be a shame to have to write a bunch of handling-loading code in every place we do this.

Code review for https://github.com/phetsims/john-travoltage/issues/128

**Comment by jbphet** [comment]
@jonathanolson - If I understand correctly, you're referring to the portion of code in `ChargeAmountSoundGenerator` that looks like this (lines 63 through 66 at the time of this writing):

```js
        // This is necessary because of the async load of the audio buffer.
        if ( !soundLoaded && typeof( sound.audioBuffer ) !== 'undefined' ) {
          soundLoaded = true;
        }
```

Sounds **are** loaded asynchronously in `Sound.js`, much as images are in other portions of our code, and if an attempt is made to play a sound in one-shot mode (i.e. play it and then stop) before the load finishes, the request is simply ignored and no sound is played.  Not a big deal.  Thus, code to check whether a sound is loaded is not necessary in most cases.  The thing that is different in this case is that the sound is being played in loop mode, i.e. continuously, and a filter cutoff frequency is being set on the sound in order to change its quality as the charge level varies.  Not playing the sound in this situaltion would be a significant issue, so code was specifically added to make sure the sound was loaded before attempting to start playing it.

It would probably be possible to hide this behind the API for `Sound.js`.  `Sound.js` could look at the play request and, if looping was specified and the sound had not yet loaded, it could queue the request and start the sound playing as soon as the load completed.  This would be a little complicated since we would also want to handle the case where playback was started and then stopped before the load completed, but it could all be done.

Back to @jonathanolson to see if adding this capability seems like a good way to go (and feel free to comment @samreid).  I'd be up for doing it, but I'd like to make sure we're clear on what would change before taking the time to implement and test any code.

**Comment by jonathanolson** [comment]
> It would probably be possible to hide this behind the API for Sound.js

I was instead recommending we handle the loading in the require.js plugin step, so that the simulation wouldn't actually "start" until the sound is loaded.

**Comment by samreid** [comment]
Yes, ideally sounds should be preloaded as well (I thought they were but it looks like I am mistaken).

**Comment by jbphet** [comment]
That sounds great.  I just looked at the `audio.js` and `Sound.js` to see if I could figure out why we are not already doing this, and I'd like to discuss what I'm seeing with @jonathanolson.  I feel like we should have this working in a way that is analogous to image loading, where the async part happens in the plugin and the wrapping of the image in a Scenery Image node is synchronous (at least I *think* that's how it works).  I'll set up a time to discuss with @jonathanolson and get to the point where I can run with it.

This issue - https://github.com/phetsims/vibe/issues/19 - might be a good one to address at the same time, since it is in the same area of code and could potentially simplify things a bit.

**Comment by jonathanolson** [comment]
This will also help a lot with the branching in RandomNodePlayer.js

**Comment by samreid** [comment]
Unassigning myself, but let me know if you need me.

**Comment by jbphet** [comment]
Async loading of sounds has been centralized into `SoundClip.js` (in the tambo repo) and `Sound.js` (in the vibe repo).  We will do some further investigation down the road on having the plugin handle the asynch loading, see https://github.com/phetsims/vibe/issues/29.  There is no longer a need for this issue, closing.
