### ISSUE TITLE
Using keyboard nav to move appendages does not transmit the state of the green box

### ISSUE THREAD

**Issue by phet-steele** [phetsims/john-travoltage#198]
The sim on the left loses the green box, while the one on the right does not. This only appears to be a problem in the state wrapper. Instance proxies behaves fine. Notice that the launched sim still has a green border around the leg, too:

![jtio03](https://cloud.githubusercontent.com/assets/5863899/22989652/eafdaac2-f373-11e6-8fcd-e9db77f14036.gif)

Seen on macOS 10.12.3 Chrome. For phetsims/tasks/issues/780.

**Comment by jessegreenberg** [comment]
This is not just an issue for keyboard nav, the green rectangle is still visible when I use the mouse.

**Comment by jessegreenberg** [comment]
I think this is fixed, but @samreid could you please verify?

**Comment by samreid** [comment]
Sure, I'm hoping to work on John Travoltage on Monday and Tuesday.

**Comment by jessegreenberg** [comment]
Sounds good, thanks!

**Comment by samreid** [comment]
The state of the visibility of the green boxes is not being transmitted, but @emily-phet and I discussed it and it may not be essential for ETS, and may not be desirable in general, since it could be nice if the customized sim still shows highlights for the draggable appendages.  I'll leave this open for further consideration, but not planning to address for the first public John Travoltage PhET-iO.

**Comment by samreid** [comment]
Here are the changes that occurred in master since this branch was created.  

![image](https://cloud.githubusercontent.com/assets/679486/23040437/88bdcb0e-f44e-11e6-9302-73636e7a3d00.png)

Based on the desired to have something published quickly and the low severity of this issue, I'm going to publish based on RC1 and we can pick up this fix (and other changes to master) in a subsequent version.

**Comment by samreid** [comment]
@jessegreenberg is working on John Travolage issues in master.  In 3 weeks or so, we'll work on rolling out another production version ready to share with our larger PhET-iO client base.

**Comment by samreid** [comment]
@jessegreenberg can you please comment on the status of this issue and let us know what's left t be done, if anything?

**Comment by jessegreenberg** [comment]
I just verified in the state wrapper that the green box state is correct.  But while using the state wrapper, I noticed there is something else wrong with the state of the charges.  Closing this issue, creating a new one for that.
