### ISSUE TITLE
Change the "rubbing" message

### ISSUE THREAD

**Issue by phet-steele** [phetsims/john-travoltage#240]
I would suggest removing "rubbing" from the message and choosing a more static verb like "touching". Technically, the leg isn't moving at all. 

Maybe:
Foot touching rug
and,
Foot off rug

For comparison, we use "pointing" for the arm, not "swinging".
Simple quick question, thoughts? @emily-phet @terracoda @jessegreenberg?

For phetsims/tasks/issues/831.

**Comment by jessegreenberg** [comment]
Also assigning @jhung in case he has thoughts on this.

**Comment by jobara** [comment]
In real life, do you need the rubbing action, as opposed to just touching, to build up the static electricity?

**Comment by emily-phet** [comment]
@phet-steele One of the goals of this simulation is to help relate a real world experience (rubbing your foot on a rug or carpet and then getting shocked) to a scenario with helpful overlays (e.g., electron representation) to help students understand the underlying physical process. Since "rubbing" is central to this physical experience, I think it's important to keep that term in, even if it may not be the most accurate term for the behavior in the sim. Additionally, when students use the sim, they are typically moving the foot pretty vigorously (especially at first), and that action "feels" like rubbing to the user. It's typically much later in play, once the student has begun to ask deeper questions and is trying to refine the boundaries of their ideas (e.g., what happens if I only add one electron to John, does my idea still hold) that movement of the foot becomes slow and more like "touching" the rug. 

For these reasons we should keep the word "rubbing" in.

**Comment by phet-steele** [comment]
@emily-phet @jobara that all makes sense. We should probably keep the word "rubbing" to tie the sim to the real world.

**Comment by phet-steele** [comment]
Thanks for the input!

**Comment by terracoda** [comment]
@emily-phet, I'm glad we are keeping the word "rubbing."
