### ISSUE TITLE
Uncaught Error: unknown value for pickable

### ISSUE THREAD

**Issue by phet-steele** [phetsims/john-travoltage#255]
Instance proxies:
1. Add electrons by rubbing the leg on the rug
2. Click ResetAll

```
Uncaught Error: unknown value for pickable
    at Object.callback (createInstanceProxyDiv.js:167)
    at dispatch (SimIFrameClient.js:155)
    at windowMessageListener (SimIFrameClient.js:198)
```
Seen on Win 10 Chrome & FF. For phetsims/tasks/issues/846. Assigning to @samreid to fix or delegate.

**Comment by EthanWJohnson** [comment]
I have a slightly different version of the same error, referencing two different locations instead;
![image](https://cloud.githubusercontent.com/assets/22551096/26700032/18c5c7ec-46d9-11e7-9a09-47ee6686310b.png)

Also, once the error occurs it duplicates indefinitely by moving either the leg or the arm; it seems to throw an error for every coordinate update that you would see in events:colorized or similar.

**Comment by samreid** [comment]
The Scenery docs say that pickable will be false, true or null, but it is coming through as `undefined`.

**Comment by samreid** [comment]
@jbphet and @ariel-phet what is the priority of this?  I know @zepumph will have a lot to do starting Monday, can you wait for him to work on this or do you need it quickly?

**Comment by jbphet** [comment]
I'm hoping to start integrating the new phet-io release of this sim plus Balloons and Static Electricity and Build an Atom on Tuesday, June 13th.  This problem seems like it would block the release of this sim, and some amount of further testing.  Working backwards a few days, I think it would be good to have it resolved and rolled into new RCs by next Thursday, June 8th.

**Comment by zepumph** [comment]
The first problem was that this pickable undefined error was downstream of the actual error, so above I added error handling to createInstanceProxyDiv.js. Now if there are errors with the invoke calls, it will error out. I'm not sure if this should be the final solution, because it is sort of like assertions in that we don't want to purposefully throw errors in production mode. This way is good for now though because it throws the actual error, yielding good info that can be used to track this stuff down. Basically this ended up being a small bug fix in JT, not perpetual through other sims. I will publish another version and give it back to QA soon. 

Commits are just in master now.

**Comment by zepumph** [comment]
@samreid can you comment on me throwing the errors from `.invoke` calls in createInstanceProxyDiv.js?

**Comment by zepumph** [comment]
There are more issues than just this from https://github.com/phetsims/tasks/issues/846, so I will wait to release a new RC for all of the problems.

**Comment by phet-steele** [comment]
I don't see the error anymore. Keeping open and assigned to @samreid since @zepumph requested a comment in https://github.com/phetsims/john-travoltage/issues/255#issuecomment-306357862 (and I don't see a comment yet).

**Comment by samreid** [comment]
@zepumph and I discussed adding a console.error statement to SimIFrameClient so that we get this kind of benefit for all wrappers, then we can eliminate this workaround in createInstanceProxyDiv.  It sounds reasonable to me since we never use Errors to pass normal information--they always indicate that something has gone wrong.  Hence it is OK to console.error them when they occur. 
 @zepumph does that sound good to you?

**Comment by zepumph** [comment]
One thought about this. We implemented this in SimIFrameAPI already. There is a console.error whenever there is a problem with the sim. 
```js
      try {

        returnValue = this.invoke( eventSource, request.protocol, parentRequest, phetioID, method, request.args, signature );
      }
      catch( e ) {
        console.error( 'SimIFrameAPI Invocation Error:', e );
        error = e;
      }
```

Why do we need it in both places? Isn't that redundant. Instead I was focused on implementing throwing the error only in Instance Proxies, since I thought of it as a good place to get that feedback, both while PhET develops it internally, and for third parties as they develop.

**Comment by zepumph** [comment]
My commit above, where I am throwing errors in Instance Proxies, was meant to be a wrapper implementation, and I stand by that. I think that error control like this (throwing them) should be done in the wrapper, and not by phet-io (which to me includes simIFrameClient).

**Comment by zepumph** [comment]
Let's talk about this more this week, perhaps just a few more minutes would be helpful.

**Comment by zepumph** [comment]
@samreid agrees, the sim side error log is enough. I should revert the error handling in instance proxies, it is no longer needed.

**Comment by zepumph** [comment]
I reverted the error handling in createInstanceProxyDiv. Closing
