### ISSUE TITLE
User suggestion: show actual charge distributions

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/john-travoltage#289]
> I was wondering if there were any plans to revisit it and possibly show the actual charge distributions. As it is, it show charges “flowing” freely from the carpet to the shoe, through the body and to the knob; a big idea in showing students how this works lies in showing how the shoes collect electrons from the carpet, accumulating on the shoe where they’re “stuck” on the insulating shoes, which polarizes the body by repelling electrons within the person. These electrons then escape when contact is made with the knob.
> 
> Just curious, as I know y’all must already be so inundated with these projects.

**Comment by jessegreenberg** [comment]
@ariel-phet @samreid do you have any thoughts on this? Assigning to both of you because @samreid is listed as one of lead design for this sim in credits.

**Comment by samreid** [comment]
Thanks for pointing this out, I was unaware that the electrons get on the shoes.  If that's correct, I guess the sim is accurate if you consider the blue spheres as charge differences (instead of electrons).  However, the nature of electrons getting stuck on the shoes seems to be outside of the learning goals of the sim--and some teachers may be able to leverage Balloons and Static Electricity for that.  I wouldn't be opposed to a "show charges" vs "show charge differences" in a future version of John Travoltage, but that doesn't seem essential for the near future for the reasons mentioned above.

**Comment by ariel-phet** [comment]
For one, I don't think the user is actually quite correct. Since you "discharge" with a spark when you touch a doorknob, there needs to be an actual flow of *excess* charge off your body, and that excess charge was picked up from rubbing on the carpet. The user seems to be implying that even once you touch the doorknob there might still be excess charges on your shoes, which doesn't make much sense. You are much more akin to a conducting sphere, than to an insulating balloon. 

Anyhow, what the user is requesting is just beyond the scope of this simulation. 

@oliver-phet feel free to let this user know we do not plan to make this change.

**Comment by oliver-phet** [comment]
Replied to user. Closing.
