### ISSUE TITLE
Final feedback - JT with Sound

### ISSUE THREAD

**Issue by emily-phet** [phetsims/john-travoltage#299]
@jbphet has the final implementation of Ashton's specs for sound design for JT. 

You all have been involved with feedback on the sound design for this sim at various points, and I wanted to give you a chance to provide feedback on this last step. We are at the point of 'decibel polishing' - tweaks to the relative volume of individual sounds. If there are no strong feelings on relative volumes, we'll proceed with this version. 

Please 1) let me know if you want to give feedback, and comment with your feedback below. If you want to provide feedback, but can't do so by end of day Tuesday, please let me know when you can.

Also - please let me know if I've missed someone who should be included. 

https://phet-dev.colorado.edu/html/john-travoltage/1.5.0-dev.3/phet/john-travoltage_en_phet.html?supportsSound&supportsEnhancedSound

**Comment by arouinfar** [comment]
Exciting news @emily-phet! JT is sounding pretty awesome to me. I don't have any decibel polishing to request, but thanks for including me. :)

**Comment by terracoda** [comment]
**Without Voice Over on**, I think the sounds are a good volume. The Reset All might be a tiny bit loud, but it is a reset, so maybe it should stand out? I'll leave that decision to the sound experts.

**With Voice Over on and audio sound ducking checked**, I find the sounds a little too quiet, especially the Hand position slider sound. If I pause interaction, i can hear the electrons on body buzz, but I only noticed it when I had a good amount of charge on John's body (more 10 charges).

**With Voice On and audio sound ducking not checked**, the sound was louder much more like and possible the same as without voice over on, and I thought that level was pretty good.

My only concern is the for the Hand position because it is a discrete sound, AT is always talking while it is playing, so it is the toughest one to hear when interaction is happening with the Hand. If there is room to make the default for the Hand position a little louder, it might be beneficial to blind users without causing annoyance to sighted users. I find the Hand position sound pleasant, so personally a little more volume would not bother me.

Overall, the sound design is awesome! Nice work!

**Comment by terracoda** [comment]
I did find an issue with the Mute Sound button which I posted in #300.

**Comment by jhung** [comment]
@emily-phet I tested this on Safari with external powered speakers, the laptop speakers, and with headphones.

The only feedback I have is that with headphones, the rubbing forward sounds a bit louder than rubbing backward. To me this sounds like the forward leg swing is more vigorous which implies more static charge generated than swinging leg backward. This could be an auditory illusion because the pitch is increasing swinging forward.

With external speakers, this didn't appear to be a problem.

Also, I'm perceiving that the rubbing volume increases with the number of charges. Is this correct? To me this could be interpreted as a harder rub.

**Comment by terracoda** [comment]
@emily-phet, note, I only tested with headphone :-)

**Comment by ariel-phet** [comment]
I tested with external speakers (Win 7 FF)

I hear what @jhung noticed with foot rubbing forward vs backwards. With my setup at least, I think the foot rubbing sound could be slightly more "muffled" and maybe that would cure the issue on its own.

Overall, things are sounding good, but one bug I noticed is that if you use the sim in "Van de Graff" mode -- as in if you put JT's hand near the doorknob, get a spark going and continuously rub the foot so there is a constant spark, you will see the constant spark but the "sparking sound" goes away. That seems problematic since the visual/model is not matching up with the produced sound.

**Comment by amanda-phet** [comment]
The relative volumes seem fine to me.

**Comment by jbphet** [comment]
I have two things for discussion:

+ On some sound systems, I notice an odd sounding high frequency component in the loop sound used to convey charges in the body.  How audible it is seems to depend a lot on the speakers used, and I found it most noticeable on a fairly recent MacBook Pro.  I could hear it in headphones if I listened closely.
+ I recently asked @Ashton-Morris for a modified version of the reset-all sound that removed a "sweep" sound effect that was present but fairly quiet relative to the rest of the sound.  That modified version is what was used in this dev version, i.e. v1.5.0-dev.3.  This isn't exactly the sound that was present in the original sound design, though, so I wanted to make sure that others didn't feel strongly that the "sweep" added value to the sound.  To compare the two, you can run [v1.5.0-dev.2](https://phet-dev.colorado.edu/html/john-travoltage/1.5.0-dev.2/phet/john-travoltage_en_phet.html?supportsSound&supportsEnhancedSound), which includes the sweep in the reset, side-by-side with [v1.5.0-dev.3](https://phet-dev.colorado.edu/html/john-travoltage/1.5.0-dev.3/phet/john-travoltage_en_phet.html?supportsSound&supportsEnhancedSound).

**Comment by emily-phet** [comment]
@jbphet For the second topic, I'm good with the sweep-free reset. I believe the intention was to cue 'erasing' - which is a nice cue. I think it's not necessary, though, and the sound is (humorously) 'cleaner' without the sweep. :)

**Comment by jbphet** [comment]
This was reviewed today with @emily-phet and @Ashton-Morris and we decided to adjust the volume of the reset all button and address the electric discharge issue (actually, I've already fixed it).  The issue that was raised about the difference in level between the forward and backward direction of the foot must be either due to the "auditory illusion" that @jhung mentioned or the headphones on which is was tested, because there is no volume change being made in the code, just a change in the center frequency of the filter that's filtering the noise.  We've decided to leave it as is for now.

We also decided to leave the charges-in-body sound as it is - the buzzing sound mentioned above is hardly noticeable in most cases and kind of works for conveying the idea of charge when it *is* noticeable.

That's it, closing.
