### ISSUE TITLE
investigate use of NoiseGenerator

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/john-travoltage#305]
Related to tambo code review, https://github.com/phetsims/tambo/issues/39.

As part of this code review, I was pointed to John Travoltage to see how the tambo API is used.  Most of that was straightforward.  But `FootDragSoundGenerator` seems a little odd.  It extends `SoundGenerator`, but does all of the work via composition with `NoiseGenerator` (part of tambo, and itself a subtype of `SoundGenerator`).   I discussed with @jbphet, and he's going to look at why (and whether) this is necessary.   From my perspective, it seems like `FootDragSoundGenerator ` should simply extend`NoiseGenerator`, and if that's not the case then I think there's a problem.

**Comment by jbphet** [comment]
Good observation.  I used composition originally because I wanted to put an additional gain stage in without worrying about what the sound manager does to the SoundGenerator base type's master gain stage, since it uses it for muting disabling sound generators.  When I thought about this, it shouldn't be necessary, since SoundGenerator keeps track of the output level even when the sound generator is disabled.  So, I tried simplifying FootDragGenerator to inherit from NoiseGenerator (which simplifies the code quite a bit), and it appears to work fine.  I think that's it for this issue, closing.
