### ISSUE TITLE
Consider improvement to swipe to focus gesture for self-voicing on touch

### ISSUE THREAD

**Issue by terracoda** [phetsims/john-travoltage#364]
Swipe to focus gesture is working great in #355.

I have 1 suggestion for improvement, and this can be for down the road, so I am creating a new issue.

I think it would be very useful to have an option to add the name of the thing that is to be grabbed and dragged, for example:
- Tap and hold to grab and drag {{hand}}.
- Tap and hold to grab and drag {{foot}}.

For Gravity Force Lab: Basics it might be much more needed than in JT:
- Tap and hold to grab and drag {{mass 1, blue sphere}}.
- Tap and hold to grab and drag {{mass 2, red sphere}}.

In GFLB, this potential space provides an opportunity to bring in the word "sphere" and the "color" of each mass sphere which are prominent in the visual design and not present in the interactive part of the Self-Voicing. These details are available, of course, in the read-me buttons. So, it is not like these details are not in the design at all. It is just that they are not immediately available.

We should consider if it is feasible now for JT, or soon for GFLB, or never.

**Comment by jessegreenberg** [comment]
We can do this now - it isn't a big effort for these two sims. However, my recommendation would be to find a single string that works for all draggable things because it will become a larger long term cost to design and develop this string for every single draggable element moving forward. 

In my opinion, the user knows what they are on from other information on focus, so "Tap and hold to grab and drag" seems like plenty to me. But happy to proceed if you still think it is best @terracoda.

**Comment by terracoda** [comment]
@jessegreenberg, this issue is related to my comments in a GFLB issue. I will add that comment here, too.

**Comment by emily-phet** [comment]
This was implemented in preparation for pre-Thanksgiving interviews in Saint Louis.

**Comment by terracoda** [comment]
What was implemented for JT was:

 -  Tap, hold, and drag to {{move hand}}.
 -  Tap, hold, and drag to {{rub foot}}.
