### ISSUE TITLE
Changes during "self-voicing sprint"

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/john-travoltage#377]
@emily-phet @terracoda @Matthew-Moore240 and I met today to sprint through remaining issues and design considerations for the self-voicing feature in john-travoltage in preparation for interviews in a couple weeks.  This issue tracks commits and other notes.

**Comment by jessegreenberg** [comment]
To summarize the real-time changes we made today:
- Arm/Leg alerts are assertive on initial pickup, but otherwise polite so they don't interrupt themselves.
- The leg position is only described on pickup/release. Otherwise, user only hears about charge pickup during drag.
- The Arm position is described during drag, once every time the arm stops moving to avoid a pileup of these alerts.
- "Rubbing" was added to the charge alert, to indicate that this is what the leg is doing to pickup charge.
- Hand label was changed to "Arm Swing", "Hand" added to all aria-valuetext for the hand. This change impacts the PDOM as well.
- Movement direction was removed from arm aria-valuetext to avoid it "closer/farther" from being read on focus. It was removed from PDOM strings as well. Perhaps in the future this kind of thing can be added again as a context response.

There were a few more things we wanted to do, but they are captured in separate issues. This can be closed.

**Comment by terracoda** [comment]
I am not liking the repetition and time of the self-voicing design of John Travoltage. I would like to review the current version of John Travoltage in detail to make sure the changes we made above were indeed what we wanted.

Things I think are problematic:
- "arm swing" in aria-valuetext
-  repetition of arm swing at start and end of interaction
- timing - how can we make sure responses don't pile-up too much causing delays. What strategies have we used in other sims? GFLB seems to work better than JT, for example.

Also, can we review the addition of "rubbing"? We have a sound for that. I am not sure we need a word for that. I think we used to have "Foot off rug" "Foot on rug". The rubbing just comes naturally if the position of the foot is in the range of "Foot on rug."

**Comment by terracoda** [comment]
Actually, "Rubbing" is part of the electron response. I don't think it is helpful because the rubbing has already happened. It's timely enough.

The issue with the sliders (for me), seems to be that the labels and position are said at start and end of drag with mouse and with every keypress. Need to lay out exactly what is happening in order to optimize the situation.

@Matthew-Moore240, do you agree we need to work on this a bit?

**Comment by terracoda** [comment]
@Matthew-Moore240, if you play with JT, you can hear how the word "Rubbing" is interrupting the qualitative amount number of charges being accumulated.

I think we should remove it, and then optimize how the Arm Swing and Leg Swing are working. The Arm Swing in particular needs to work more like the spheres in GFLB.

**Comment by terracoda** [comment]
@Matthew-Moore240 and @emily-phet, please feel free to chime in on what the arm should say.

**Comment by terracoda** [comment]
Connecting this issue to https://github.com/phetsims/john-travoltage/issues/394#issuecomment-797142077

New "helpful hints", i.e. help text for Arm and Leg Swings are posted over #394

**Comment by terracoda** [comment]
These design issues were discussed at March 16 Self-Voicing meeting. Here's the summary:

For Arm Swing interaction:
We would the Arm Swing to work like in GFLB
- on focus: Arm Swing + {{current position}} + {{Help text if checked}}
- on change in distance from doorknob: {{new position}} 

Which should result in something like this:
 -  "Arm Swing. Hand Pointing at upper door, close to doorknob. {{Help text if checked}}"
 -  "Hand close to doorknob"
 - "Hand not so close to doorknob"
 - "Hand not so close to doorknob"
 - "Hand pointing straight up"

Also remove "Rubbing" and from electrons response so responses look like this:
Change "Rubbing. {{A few}} electrons on body." to
- "{{A few}} electrons on body."
I am not sure of actual punctuation, so use what's there.

I'll add the new region "{{A couple}} electrons on body." in a new issue since it is not critical.

**Comment by jessegreenberg** [comment]
@terracoda @Matthew-Moore240 here is a new version with changes listed above. Can you please review?

https://phet-dev.colorado.edu/html/jg-tests/john-travoltage_en_phet.html?supportsSelfVoicing

**Comment by terracoda** [comment]
As I said in https://github.com/phetsims/john-travoltage/issues/394#issuecomment-800697806

This sounds awesome.

My only question is about the Leg Swing position during changes, so I will open a new issue for that.
It sounds good as is, but we might want to review the Leg Swing a little more.
