### ISSUE TITLE
(Self-Voicing) Context response for Reset All button? 

### ISSUE THREAD

**Issue by terracoda** [phetsims/john-travoltage#392]
When doing a review of Self-Voicing, I noticed that the context response for the reset all button in John Travoltage is:
 - Reset All. Sims screen restarted. Everything reset.
 
This is different from the one in Gravity Force Lab: Basics which is:
- Reset all. Everything reset.

Because mouse and touch events only trigger a context response, I decided to change the response to include the object's name (Reset all), and I thought just adding the name to the original response was a little long.

I propose the shorter version as a general (common code) change for all self-voicing designs.
@Matthew-Moore240 and @jessegreenberg, any thoughts?

**Comment by terracoda** [comment]
I have yet to hear any complaints about the regular (and longer) Reset All response.

**Comment by terracoda** [comment]
Actually, the two reset all buttons are working the same now. They both say:

- "Reset All. Sim screen restarted. Everything reset."

I thought a shorter response would be better for the voiced experience was, i.e.,:
- "Reset All. Everything reset."

In my interviews, however, no one has complained about this longer response which strings together button name and the full PDOM context response. 

We can leave it as-is, unless @BLFiedler had any complaints in his interviews with younger learners without visual impairments. Assigning to @BLFiedler for a quick check-in.

**Comment by BLFiedler** [comment]
No one made mention of the reset all in particular. I am also fine with it either way.

**Comment by terracoda** [comment]
Let's leave it as is, until we hear different.
If we leave it as is, we have alignment with the strings in the PDOM.

**Comment by terracoda** [comment]
Closing.

**Comment by terracoda** [comment]
Re-opening to make a clear decision on what's needed for the Reset All button for Voicing.

From the [JT's Voicing Design Doc](https://docs.google.com/document/d/1nHzqDbRvv-By6gYK59Al345AY7D2z87Ng2im8nf4z2w/edit)
**Notes on simple buttons and the Reset All button:** 
The Reset All button is a simple button. Pressing it causes a reset, and the button then returns to an unpressed state. A simple button does not toggle between pressed and unpressed states. Originally, I designed a custom response to include the button’s name in the response so mouse users would have access to the button’s name. This meant in some cases, one could hear “Reset All” twice. 

Here’s the original custom context response:
- Reset All. Everything reset.

The actual PDOM response is:
- Sim screen restarted. Everything reset.

For interviews, some prototypes included the longer PDOM context response, made even longer with the button’s name:
- Reset All, Sim screen restarted. Everything reset.

**Consider for future releases, or now, or never? ** 
Should we shorten the Reset All button response?  No one complained about this longer response in interviews, however, it is long. We should consider the best reset all response for the long term - strings straight from PDOM or shorter custom strings?

![Screen Shot 2021-05-03 at 3 46 24 PM](https://user-images.githubusercontent.com/1902116/116915587-c643d100-ac26-11eb-9ee0-defe166ce56e.png)

**Comment by terracoda** [comment]
Over @emily-phet for comment.

**Comment by emily-phet** [comment]
@terracoda 
The table above is super helpful! 
Here's my thoughts...
I like your suggested changes - removing "sim screen restarted". I think you can make the call on this without larger team input. @zepumph mentioned today that it's not an issue to have a static reset all button string for interactive description, and a (different) static one for voicing, so this sounds like the way to go.
In the long term, we're going to run into a situation where someone is using a physical manipulative and not attending to a screen...so it seems unlikely to me that the "sim screen restarted" will actually be the best choice of voicing description at that point. We may end up finding that for voicing, since it will span physical and virtual environments in a way that interactive description does not, we actually revisit this again in the future. For example, we may at some point find that saying "everything reset" is not working, since you can reset the "sim" without resetting the physical manipulative, but let's cross that bridge when we get to it.
In the meantime, I really like your idea above, and fully support you moving forward with having it implemented! Let me know if you want to discuss more.

**Comment by terracoda** [comment]
@emily-phet, thanks for your comments. I'll assign to @jessegreenberg to see if we can get the custom response in John Travoltage's voicing release.

**Comment by terracoda** [comment]
@jessegreenberg, over to you for comment if this feasible for JT's Voicing release.
See custom strings in https://github.com/phetsims/john-travoltage/issues/392#issuecomment-831440810
and in design doc.

**Comment by terracoda** [comment]
Adding a slightly updated and more complete screenshot of table
![Screen Shot 2021-05-03 at 5 37 17 PM](https://user-images.githubusercontent.com/1902116/116927463-445ba400-ac36-11eb-8833-3091785a2345.png)

**Comment by jessegreenberg** [comment]
The Voicing context response for the ResetAllButton has been changed in the above commits.

**Comment by jessegreenberg** [comment]
@terracoda can you please verify this is working correctly in https://phet-dev.colorado.edu/html/john-travoltage/1.6.0-preferences.6/phet/john-travoltage_en_phet.html?

**Comment by terracoda** [comment]
Thanks, sounds great. Closing.
