### ISSUE TITLE
Highlighting behaves oddly with touch

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/john-travoltage#412]
**Test device**
iPad
**Operating System**
iPadOS 14
**Browser**
Safari
**Problem description**
For https://github.com/phetsims/QA/issues/645.
Items are only highlighted with touch if the finger drags over them. If you are interacting but your finger isn't on them, or if it is a button you just press, it doesn't seem to appear.

**Visuals**

https://user-images.githubusercontent.com/41024075/117734563-f48a5900-b1b0-11eb-93bc-202b889bfef6.MP4

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/john-travoltage/issues/412#issuecomment-839142236 is fixed on master. But the other part remained a problem. I just made a change to HighlightOverlay that makes it so that the highlight for interactive highlights will not change until interaction with a particular component has finished.

**Comment by jessegreenberg** [comment]
This one is fixed, would be good to leave open to verify in next version.

**Comment by jessegreenberg** [comment]
This has been working as we want for some time now, closing this issue.
