### ISSUE TITLE
Preferences dialog does not seem to work with screen reader

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/john-travoltage#416]
For https://github.com/phetsims/QA/issues/645. Seen on iPadOS mobile VO
When using mobile VO, I had difficulty opening the Preferences dialog, and when I did open it, only some things were read out and I couldn't seem to change tabs.
The instructions were to test screen readers without turning voicing on, so I'm not sure if this is expected to work, but the preferences dialog does not seem to work with screen readers.

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe - Voicing doesn't need to work well while the screen reader is on, but the Dialog itself should still work with a Screen Reader. I will take a look.

**Comment by jessegreenberg** [comment]
Listing things I am noticing while testing myself on iOS VoiceOver
- The first time the Dialog opens, it is immediately close. The second time it seems to work well. I have seen this before, but can't remember where.
- When I activate a tab with VoiceOver, the cursor moves into the tab content automatically. Maybe this is a VO feature with role=tab? It doesn't always happen.
- Some of the content isn't readable with a screen reader, but I think that has since been resolved by #403 .

**Comment by jessegreenberg** [comment]
All of these have been fixed, closing.
