### ISSUE TITLE
Thumping sound heard in background when voicing is engaged

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/john-travoltage#434]
**Test device**
MacBook Air (M1 chip)

**Operating System**
11.4

**Browser**
chrome 91.0.4472.114

**Problem description**
https://github.com/phetsims/qa/issues/676

Thumping sound noticed when voicing was engaged. 

**Steps to reproduce**
1. Click on preferences icon in toolbar
2. Click on audio to open audio preference dialog box
3. Turn on extra sounds
4. Turn on voicing using the toggle button
5. Select the first two sim voicing options
6. Expand the customize voice panel
7. Change rate to 1.5x
8. Change pitch to low range
9. Choose Victoria in the combo box
10. Move John's arm around

I recorded the sound using Voice Memos on my iPhone. Hopefully you can hear it. 
https://drive.google.com/file/d/1D2Zp1IKKCqyhbozY-_fHvK0GpP5m9T45/view?usp=sharing 

I could not hear the sound when using the video option on my iPhone. 

**Visuals**

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪John Travoltage‬
URL: https://phet-dev.colorado.edu/html/john-travoltage/1.6.0-rc.1/phet/john-travoltage_all_phet.html
Version: 1.6.0-rc.1 2021-07-22 18:05:38 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36
Language: en-US
Window: 1262x687
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by jessegreenberg** [comment]
Thanks @Nancy-Salpepi - I had a listen to the recording and to be honest I am not able to hear any "thumping" sounds.

Also, over slack @Nancy-Salpepi said that this sound was only happening for her when using the "Victoria" voice.

I had a listen on my macOS 11.4 with "Victoria" voice at the settings described in this issue and couldn't hear any thumping. And since it is an artifact of the synth provided by the browser it likely isn't something we can resolve anyway.

@emily-phet @terracoda assigning to you to review so you are aware of this issue. Can you please comment on whether it requires more time to debug?

**Comment by jessegreenberg** [comment]
@Nancy-Salpepi also mentioned that most of the observed distortion happened when changing voice settings (rate, pitch), so that is good to know.

**Comment by emily-phet** [comment]
I suggest we don't put more effort into this now, continue with JT publication, and just keep an eye/ear out for this as we do more voicing sims.

**Comment by jessegreenberg** [comment]
Thanks @emily-phet, closing this issue then.
